server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka