server:
  port: 8083

spring:
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

  instance:
    prefer-ip-address: true

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework.web: DEBUG

  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger - correlationId=%X{correlationId} - %msg%n"

resilience4j:
  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 2s
        cancelRunningFuture: true

  thread-pool-bulkhead:
    instances:
      paymentBulkhead:
        coreThreadPoolSize: 5
        maxThreadPoolSize: 10
        queueCapacity: 20

  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 1s